# Generated by Django 5.2.1 on 2025-05-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacion', models.CharField(max_length=200, verbose_name='Designación')),
                ('descripción', models.TextField(verbose_name='Descripción')),
                ('escuela', models.CharField(choices=[('ESC_NIN', 'Ninguna'), ('ESC_CHI', 'Ispano Ingles')], max_length=64, null=True)),
                ('genero', models.CharField(choices=[('GEN_AMB', 'Ambos'), ('GEN_NO', 'Niño'), ('GEN_NA', 'Niña')], max_length=64, null=True)),
                ('estado', models.CharField(choices=[('EST_NIN', 'No precisado'), ('EST_NUEVO', 'Nuevo'), ('EST_COMNUE', 'Como nuevo'), ('EST_PRIM', 'Primera mano'), ('EST_SEC', 'Secunda mano')], max_length=64, null=True)),
                ('prenda', models.CharField(choices=[('PRD_NIN', 'Ninguno'), ('PRD_UN_PAN', 'Pantalón'), ('PRD_UN_SUE', 'Suéter'), ('PRD_UN_FAL', 'Falda'), ('PRD_UN_POL', 'Polo'), ('PRD_DP_PAN', 'Pantalón'), ('PRD_DP_BER', 'Bermuda'), ('PRD_DP_POL', 'Polo'), ('PRD_DP_CHQ', 'Chaqueta'), ('PRD_DP_CHD', 'Chandal completo')], max_length=64, null=True)),
                ('foto', models.URLField(max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['-created', 'designacion'],
            },
        ),
    ]
