# Generated by Django 5.2.1 on 2025-05-27 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_descripción_anuncio_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='talla',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('EST_ALL', 'Todos'), ('EST_NIN', 'No precisado'), ('EST_NUEVO', 'Nuevo'), ('EST_COMNUE', 'Como nuevo'), ('EST_PRIM', 'Primera mano'), ('EST_SEC', 'Secunda mano')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='genero',
            field=models.CharField(choices=[('GEN_ALL', 'Todos'), ('GEN_MX', 'Mixto'), ('GEN_NO', 'Niño'), ('GEN_NA', 'Niña')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='prenda',
            field=models.CharField(choices=[('PRD_NIN', 'Ninguno'), ('PRD_ALL', 'Todas'), ('PRD_UN', 'Todos Uniformes'), ('PRD_UN_PAN', 'Pantalón Uniforme'), ('PRD_UN_SUE', 'Suéter Uniforme'), ('PRD_UN_FAL', 'Falda Uniforme'), ('PRD_UN_POL', 'Polo Uniforme'), ('PRD_DP', 'Todos Deportes'), ('PRD_DP_PAN', 'Pantalón Deportes'), ('PRD_DP_BER', 'Bermuda Deportes'), ('PRD_DP_POL', 'Polo Deportes'), ('PRD_DP_CHQ', 'Chaqueta Deportes'), ('PRD_DP_CHD', 'Chandal completo Deportes')], max_length=64, null=True),
        ),
    ]
