# Generated by Django 5.2.1 on 2025-05-28 10:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anuncio_talla_anuncio_usuario_alter_anuncio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='escuela',
            field=models.CharField(choices=[('ESC_NIN', 'Ninguna'), ('ESC_CHI', 'Hispano Inglés')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.custom_upload_to),
        ),
    ]
