# Generated by Django 5.2.1 on 2025-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mensaje_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='interesados',
            field=models.SmallIntegerField(default=0),
        ),
    ]
