# Generated by Django 5.2.1 on 2025-06-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_anuncio_interesados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='interesados',
            new_name='mensajes',
        ),
    ]
