# Generated by Django 5.2.1 on 2025-06-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_interesados_anuncio_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='materia',
            field=models.CharField(choices=[('MAT_ALL', 'Todos'), ('MAT_MZ', 'Mezcla'), ('MAT_AG', '100% Algodon/Lana'), ('MAT_SY', '100% Syntetico')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('EST_ALL', 'No precisado'), ('EST_NUEVO', 'Nuevo'), ('EST_COMNUE', 'Como nuevo'), ('EST_PRIM', 'Primera mano'), ('EST_SEC', 'Secunda mano')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='prenda',
            field=models.CharField(choices=[('PRD_ALL', 'Lote'), ('PRD_POL', 'Polo'), ('PRD_JER', 'Jersey'), ('PRD_FAL', 'Falda'), ('PRD_PAN', 'Pantalón'), ('PRD_CHD', 'Chandal'), ('PRD_BER', 'Bermuda'), ('PRD_BAB', 'Babi')], max_length=64, null=True),
        ),
    ]
