# Generated by Django 5.2.1 on 2025-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_anuncio_materia_alter_anuncio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='talla',
            field=models.CharField(choices=[('74', '00'), ('78', '0'), ('82', '1'), ('98', '2'), ('108', '4'), ('118', '6'), ('128', '8'), ('140', '10'), ('152', '12'), ('164', '14'), ('170', '16 / S / 2A'), ('178', '18 / M / 3A'), ('184', '20 / L / 4A'), ('188', '22 / XL / 5A'), ('192', '24 / XXL / 6A')], max_length=64, null=True),
        ),
    ]
