# Generated by Django 5.2.1 on 2025-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_anuncio_escuela_alter_anuncio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='prenda',
            field=models.CharField(choices=[('PRD_ALL', 'Multi'), ('PRD_POL', 'Polo'), ('PRD_JER', 'Jersey'), ('PRD_FAL', 'Falda'), ('PRD_PAN', 'Pantalón'), ('PRD_CHD', 'Chandal'), ('PRD_BER', 'Bermuda'), ('PRD_BAB', 'Babi')], max_length=64),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='talla',
            field=models.CharField(choices=[('TAL_ALL', 'No precisado'), ('74', '00'), ('78', '0'), ('82', '1'), ('98', '2'), ('108', '4'), ('118', '6'), ('128', '8'), ('140', '10'), ('152', '12'), ('164', '14'), ('170', '16 / S / 2A'), ('178', '18 / M / 3A'), ('184', '20 / L / 4A'), ('188', '22 / XL / 5A'), ('192', '24 / XXL / 6A')], max_length=64),
        ),
    ]
