# Generated by Django 5.2.1 on 2025-06-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_anuncio_prenda_alter_anuncio_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='genero',
        ),
    ]
