# Generated by Django 5.2.1 on 2025-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_anuncio_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
