# Generated by Django 5.2.1 on 2025-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_anuncio_prenda_alter_anuncio_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='prenda',
            field=models.CharField(choices=[('PRD_MLT', 'Multi'), ('PRD_POL', 'Polo'), ('PRD_JER', 'Jersey'), ('PRD_FAL', 'Falda'), ('PRD_PAN', 'Pantalón'), ('PRD_CHD', 'Chándal'), ('PRD_BER', 'Bermuda'), ('PRD_BAB', 'Babi')], max_length=64),
        ),
    ]
