# Generated by Django 5.2.1 on 2025-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_anuncio_prenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(blank=True, choices=[('EST_ALL', 'No precisado'), ('EST_NUEVO', 'Nuevo'), ('EST_COMNUE', 'Como nuevo'), ('EST_PRIM', 'Primera mano'), ('EST_SEC', 'Segunda mano')], max_length=64, null=True),
        ),
    ]
